FROM alpine:edge AS arm-ex
RUN apk update && \
	apk add p7zip wget qemu && \
	mkdir -p system && \
	wget https://dl.google.com/android/repository/sys-img/google_apis/armeabi-v7a-25_r15.zip && \
	7z x armeabi-v7a-25_r15.zip armeabi-v7a/system.img && \
	7z x armeabi-v7a-25_r15.zip armeabi-v7a/ramdisk.img && \
	7z x armeabi-v7a/system.img -oarmeabi-v7a && \
	7z x armeabi-v7a/ramdisk.img -oarmeabi-v7a && \
	cpio -i -F armeabi-v7a/system -p system && \
	cpio -i -F armeabi-v7a/ramdisk -p system

FROM scratch
COPY --from=arm-ex system/ /
ENTRYPOINT ["/init"]
