FROM alpine:edge AS arm-ex
RUN apk update && \
	apk add p7zip wget qemu && \
	mkdir -p init system && \
	wget https://dl.google.com/android/repository/sys-img/google_apis/armeabi-v7a-25_r15.zip && \
	7z x armeabi-v7a-25_r15.zip armeabi-v7a/system.img && \
	7z x armeabi-v7a/system.img . -o system && \
	7z x armeabi-v7a/ramdisk.img . -o init

FROM scratch
COPY --from=arm-ex system/ init/ /
