FROM alpine:edge AS aarch64-ex
RUN apk update && \
	apk add p7zip wget qemu && \
	mkdir -p system/data/etc && \
	wget https://dl.google.com/android/repository/sys-img/google_apis/arm64-v8a-25_r15.zip && \
	7z x arm64-v8a-25_r15.zip arm64-v8a/system.img && \
	7z x arm64-v8a-25_r15.zip arm64-v8a/ramdisk.img && \
	7z x arm64-v8a-25_r15.zip arm64-v8a/userdata.img && \
	7z x arm64-v8a-25_r15.zip arm64-v8a/encryptionkey.img && \
	7z x arm64-v8a/system.img -osystem && \
	7z x arm64-v8a/ramdisk.img -osystem && \
	7z x arm64-v8a/userdata.img -osystem && \
	mv arm64-v8a/encryptionkey.img system/data/etc/encryptionkey.img && \
	cd system && \
	cpio -i -F ramdisk && \
	rm ramdisk

FROM scratch
COPY --from=aarch64-ex system/ /
ENTRYPOINT ["/init"]
